CREATE OR REPLACE VIEW BILLS_PROSPECT.VW_BILL_TRANSACTIONS AS
SELECT
  CUSTOMER_ID,
  SUM(AMOUNT) AS TOTAL_AMOUNT,
  COUNT(*) AS TOTAL_TRANSACTIONS
FROM BILLS_PROSPECT.BILL_TRANSACTIONS
GROUP BY CUSTOMER_ID;
